version: "3.9"
services:
  app:
    container_name: pen-dev-server
    image: pen-dev-server
    build:
      context: ./
      target: development
    ports:
      - "4000:4000"
      - "9229:9229"
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command:
      - yarn
      - watch:all
    depends_on:
      - db
  db:
    image: postgres:10.16
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: liyelp_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
